Repository ow2-proactive/scheduling-abstraction-layer, pull requests merged in 2023-07, with the labels that each got.

#52 Handle shadow components and improve multiple communications
  sal-common/src/main/java/org/ow2/proactive/sal/model/Job.java
  sal-common/src/main/java/org/ow2/proactive/sal/model/Port.java
  sal-common/src/main/java/org/ow2/proactive/sal/model/Task.java
  sal-service/src/main/java/org/ow2/proactive/sal/service/service/JobService.java
  sal-service/src/main/java/org/ow2/proactive/sal/service/service/MonitoringService.java
  sal-service/src/main/java/org/ow2/proactive/sal/service/service/ScalingService.java
  sal-service/src/main/java/org/ow2/proactive/sal/service/service/TaskBuilder.java
  sal-service/src/main/java/org/ow2/proactive/sal/service/service/TaskService.java
  sal-service/src/main/resources/clean_synchronization_channels_script.groovy
  sal-service/src/main/resources/collect_ip_addr_results.groovy
  sal-service/src/main/resources/collect_ip_addr_to_env_vars_script.groovy
  sal-service/src/main/resources/export_env_var_script.sh
  sal-service/src/main/resources/init_synchronization_channels_script.groovy
  sal-service/src/main/resources/post_prepare_infra_script.groovy
  sal-service/src/main/resources/prepare_infra_script.sh
Labels: enhancement

#53 Fix commands implementation script order and improve post prepare infra logs
  sal-service/src/main/java/org/ow2/proactive/sal/service/service/TaskBuilder.java
  sal-service/src/main/resources/post_prepare_infra_script.groovy
Labels: enhancement

#54 Fix ports to open update when requiring component is being deleted during reconfiguration
  sal-service/src/main/java/org/ow2/proactive/sal/service/service/MonitoringService.java
  sal-service/src/main/java/org/ow2/proactive/sal/service/service/TaskService.java
Labels: bug

#55 Fix init and clean channels dependency for shadow tasks and clean data
  sal-common/src/main/java/org/ow2/proactive/sal/model/ByonNode.java
  sal-common/src/main/java/org/ow2/proactive/sal/model/CloudConfiguration.java
  sal-common/src/main/java/org/ow2/proactive/sal/model/DockerEnvironment.java
  sal-common/src/main/java/org/ow2/proactive/sal/model/EdgeNode.java
  sal-common/src/main/java/org/ow2/proactive/sal/model/Job.java
  sal-common/src/main/java/org/ow2/proactive/sal/model/PACloud.java
  sal-common/src/main/java/org/ow2/proactive/sal/model/Task.java
  sal-service/src/main/java/org/ow2/proactive/sal/service/service/JobService.java
  sal-service/src/main/java/org/ow2/proactive/sal/service/service/RepositoryService.java
Labels: bug

#56 Fix JDBC errors when addinng monitors while adding nodes
  sal-service/src/main/java/org/ow2/proactive/sal/service/service/MonitoringService.java
  sal-service/src/main/java/org/ow2/proactive/sal/service/service/NodeService.java
  sal-service/src/main/java/org/ow2/proactive/sal/service/service/ReconfigurationService.java
Labels: bug

#57 Fix cleanAll endpoint used in purgesal script to clean DB
  sal-service/src/main/java/org/ow2/proactive/sal/service/service/RepositoryService.java
Labels: bug

#58 A fix for removing cloud deployments when the cloud is removed
  sal-service/src/main/java/org/ow2/proactive/sal/service/nc/NodeCandidateUtils.java
  sal-service/src/main/java/org/ow2/proactive/sal/service/service/CloudService.java
  sal-service/src/main/java/org/ow2/proactive/sal/service/service/RepositoryService.java
Labels: bug

#59 Improve README file
  README.md
Labels: documentation, enhancement
